// shared/helpers/action_types.js
module.exports = {
  SERVER_DATA: 'SERVER_DATA',
  SERVER_ERROR: 'SERVER_ERROR',
  SERVER_AGREEMENT_POST: 'SERVER_AGREEMENT_POST',
  CONTACT_POST: 'CONTACT_POST',
  SERVER_EQUIPMENT_POST: 'SERVER_EQUIPMENT_POST',
  SERVER_SCRIPT_POST: 'SERVER_SCRIPT_POST',
  SERVER_SCRIPT_QUERY: 'SERVER_SCRIPT_QUERY',
  SERVER_SOUND_POST: 'SERVER_SOUND_POST',
  SERVER_SOUND_QUERY: 'SERVER_SOUND_QUERY',
}
